# Generated by cpp11: do not edit by hand

adf_upper <- function(x, intl) {
  .Call(`_adfExplorer_adf_upper`, x, intl)
}

adf_path_to_entry <- function(extptr, filename, mode) {
  .Call(`_adfExplorer_adf_path_to_entry`, extptr, filename, mode)
}

adf_file_exists_ <- function(extptr, path) {
  .Call(`_adfExplorer_adf_file_exists_`, extptr, path)
}

adf_dir_exists_ <- function(extptr, path) {
  .Call(`_adfExplorer_adf_dir_exists_`, extptr, path)
}

adf_entry_info_ <- function(extptr, path, mode) {
  .Call(`_adfExplorer_adf_entry_info_`, extptr, path, mode)
}

adf_con_summary <- function(extptr) {
  .Call(`_adfExplorer_adf_con_summary`, extptr)
}

adf_file_read_ext <- function(extptr, req_size) {
  .Call(`_adfExplorer_adf_file_read_ext`, extptr, req_size)
}

adf_change_dir <- function(extptr, path) {
  .Call(`_adfExplorer_adf_change_dir`, extptr, path)
}

adf_get_current_dir <- function(extptr) {
  .Call(`_adfExplorer_adf_get_current_dir`, extptr)
}

list_adf_entries_ <- function(extptr, filename, recursive, nested) {
  .Call(`_adfExplorer_list_adf_entries_`, extptr, filename, recursive, nested)
}

adf_mkdir <- function(extptr, path) {
  .Call(`_adfExplorer_adf_mkdir`, extptr, path)
}

adf_remove_entry <- function(extptr, path, flush) {
  .Call(`_adfExplorer_adf_remove_entry`, extptr, path, flush)
}

adf_set_entry_name_ <- function(extptr, path, replacement) {
  .Call(`_adfExplorer_adf_set_entry_name_`, extptr, path, replacement)
}

move_adf_internal <- function(extptr, source, destination) {
  .Call(`_adfExplorer_move_adf_internal`, extptr, source, destination)
}

adf_readbin_size <- function(what, sz) {
  .Call(`_adfExplorer_adf_readbin_size`, what, sz)
}

adf_readlines <- function(extptr, n_, ok, warn, encoding, skipNul) {
  .Call(`_adfExplorer_adf_readlines`, extptr, n_, ok, warn, encoding, skipNul)
}

adf_writebin <- function(object, extptr, size, swap, useBytes) {
  .Call(`_adfExplorer_adf_writebin`, object, extptr, size, swap, useBytes)
}

adf_writelines <- function(text, extptr, sep, useBytes) {
  .Call(`_adfExplorer_adf_writelines`, text, extptr, sep, useBytes)
}

get_bitmap <- function(extptr, vol_num) {
  .Call(`_adfExplorer_get_bitmap`, extptr, vol_num)
}

read_adf_block_ <- function(extptr, sector) {
  .Call(`_adfExplorer_read_adf_block_`, extptr, sector)
}

write_adf_block_ <- function(extptr, sector, block) {
  .Call(`_adfExplorer_write_adf_block_`, extptr, sector, block)
}

interpret_file_header <- function(extptr, vol_num, sectnum) {
  .Call(`_adfExplorer_interpret_file_header`, extptr, vol_num, sectnum)
}

interpret_dir_header <- function(extptr, vol_num, sectnum) {
  .Call(`_adfExplorer_interpret_dir_header`, extptr, vol_num, sectnum)
}

interpret_root_header <- function(extptr, vol_num) {
  .Call(`_adfExplorer_interpret_root_header`, extptr, vol_num)
}

adf_dev_format <- function(extptr, name, ffs, intl, dircache, bootable) {
  .Call(`_adfExplorer_adf_dev_format`, extptr, name, ffs, intl, dircache, bootable)
}

adf_dev_name <- function(extptr, vol_num) {
  .Call(`_adfExplorer_adf_dev_name`, extptr, vol_num)
}

adf_dev_size <- function(extptr) {
  .Call(`_adfExplorer_adf_dev_size`, extptr)
}

adf_dev_nvol <- function(exptr) {
  .Call(`_adfExplorer_adf_dev_nvol`, exptr)
}

adf_dev_type <- function(exptr) {
  .Call(`_adfExplorer_adf_dev_type`, exptr)
}

adf_free_blocks <- function(exptr, vol_num) {
  .Call(`_adfExplorer_adf_free_blocks`, exptr, vol_num)
}

adf_block_size <- function(exptr, vol_num) {
  .Call(`_adfExplorer_adf_block_size`, exptr, vol_num)
}

adf_vol_size <- function(exptr, vol_num) {
  .Call(`_adfExplorer_adf_vol_size`, exptr, vol_num)
}

adf_is_intl <- function(exptr, vol_num) {
  .Call(`_adfExplorer_adf_is_intl`, exptr, vol_num)
}

adf_is_dircache <- function(exptr, vol_num) {
  .Call(`_adfExplorer_adf_is_dircache`, exptr, vol_num)
}

adf_is_ffs <- function(exptr, vol_num) {
  .Call(`_adfExplorer_adf_is_ffs`, exptr, vol_num)
}

adf_is_write_protected <- function(exptr) {
  .Call(`_adfExplorer_adf_is_write_protected`, exptr)
}

adf_is_bootable <- function(exptr, vol_num) {
  .Call(`_adfExplorer_adf_is_bootable`, exptr, vol_num)
}

adf_set_dev_name <- function(extptr, vol_num, new_name) {
  .Call(`_adfExplorer_adf_set_dev_name`, extptr, vol_num, new_name)
}

open_adf_ <- function(filename, write_protected) {
  .Call(`_adfExplorer_open_adf_`, filename, write_protected)
}

close_all_devices_ <- function() {
  invisible(.Call(`_adfExplorer_close_all_devices_`))
}

adf_close_file_con <- function(extptr) {
  invisible(.Call(`_adfExplorer_adf_close_file_con`, extptr))
}

seek_adf <- function(extptr, where, origin) {
  .Call(`_adfExplorer_seek_adf`, extptr, where, origin)
}

adf_file_con_ <- function(extptr, filename, writable) {
  .Call(`_adfExplorer_adf_file_con_`, extptr, filename, writable)
}

adf_file_con_info <- function(extptr) {
  .Call(`_adfExplorer_adf_file_con_info`, extptr)
}

close_adf <- function(extptr) {
  invisible(.Call(`_adfExplorer_close_adf`, extptr))
}

dumpster_dive <- function(extptr, vol_num) {
  .Call(`_adfExplorer_dumpster_dive`, extptr, vol_num)
}

undelete_adf_entry <- function(extptr, vol_num, sect) {
  .Call(`_adfExplorer_undelete_adf_entry`, extptr, vol_num, sect)
}
